# Generated by Django 4.1.7 on 2023-04-20 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employeetraining',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeetraining',
            name='training',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='training',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='due_date',
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='EmployeeTraining',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.AddField(
            model_name='trainingstatus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AddField(
            model_name='trainingstatus',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.training'),
        ),
    ]
